### ISSUE TITLE
Error message while trying to install the extension

### ISSUE THREAD

**Issue by atang35** [mvuorre/quarto-preprint#10]
Perhaps I am doing something wrong, however, running `quarto add template mvuorre/preprint` or `quarto use template mvuorre/preprint` results in an error message: "ERROR: Too many arguments: mvuorre/preprint"
<img width="501" alt="Screenshot 2024-07-01 at 2 05 22 PM" src="https://github.com/mvuorre/quarto-preprint/assets/37811105/37f82117-a159-4e08-ab01-e8c2820fcbde">

**Comment by franfrutos** [comment]
Hey! Same thing happened to me. You just need to change **preprint** to **quarto-preprint** and that's it.

**Comment by atang35** [comment]
thank you so much. I will try it

**Comment by mvuorre** [comment]
Yes this was fixed by @franfrutos in #11 (thanks!).
