### ISSUE TITLE
Set paragraph spacing properly

### ISSUE THREAD

**Issue by mvuorre** [mvuorre/quarto-preprint#13]
https://github.com/mvuorre/quarto-preprint/blob/2280fd88ad24e5b0eb4826078f2a923b7597f4b9/_extensions/preprint/typst-template.typ#L120

https://staging.typst.app/docs/reference/model/par/#parameters-spacing

**Comment by danieltomasz** [comment]
How I set this is between versions  
```
//show par: set block(spacing: spacing)

if sys.version >= version(0,12,0) {
  set par(spacing: spacing)
} else {
  show par: set block(spacing: spacing)
}
```

A relevant reference from typst forum https://forum.typst.app/t/how-to-change-text-spacing/1121/2
