### ISSUE TITLE
[Documention] Fix to template installation syntax

### ISSUE THREAD

**Issue by danieltomasz** [mvuorre/quarto-preprint#20]
In the README.md is
```
quarto add template mvuorre/quarto-preprint
```
it gives
```
ERROR: Too many arguments: mvuorre/quarto-preprint
```
it should be  probably 

```
quarto add mvuorre/quarto-preprint
```
Similarly for the second example.

( I  tested  on quarto  1.5 and 1.6)

**Comment by danieltomasz** [comment]
Also personally I would say would useful to warn users in README about this bug  "et all" https://github.com/quarto-dev/quarto-cli/issues/10105
an potential workaround with setting QUARTO_TYPST=/path/to/typst0.11.1, it would really save me several hours today :)

**Comment by mvuorre** [comment]
Thanks, I'll fix some of these in the near future. I hesitate to set env variables etc because want to keep this as light weight as possible on my side, so prolly a note on requiring certain versions is for me more appropriate.

**Comment by mvuorre** [comment]
I just fixed this in ada4a3e, and hesitant to add a known bugs thing into the readme (they are upstream and reported in github issues) or env variables to make my life easier. Happy to hear thoughts before closing though (and much appreciate already).

(Why is it `quarto add mvuorre/quarto-preprint` but then `quarto use template mvuorre/quarto-preprint` ahhh)

**Comment by danieltomasz** [comment]
> I just fixed this in https://github.com/mvuorre/quarto-preprint/commit/ada4a3e46b20230a6354f4d6eb580eb45742d7e8, and hesitant to add a known bugs thing into the readme (they are upstream and reported in GitHub issues) or env variables to make my life easier
I think it could be just as pinned issue, I could create a separate one with my solution, and the label wontfix/upstream can be applied

When  I started using the template, suppression of et all was for me  really confusing, since it happened only you cite something twice, my first idea was that something was wrong with the bibliographic entry ; 
- I installed both typst `0.11.1` which solves the issue without warnings about other things
-  I tried also  `0.12`  which solves this as well. additionally I can  use custom local CSL with typst, but it will gives me a bunch of depredations  + one settings about paragraph need to be changed, otherwise is fine

> I hesitate to set env variables etc because want to keep this as light weight as possible on my side (and so wait for upstream fixes

My idea wasn't to set any variable with this extension, rather just to add a section to readme, stating about known bugs - "suppression of et al" and until upstream quarto will ship updated typst users if they really need may try to install typst 0.11.1 via official installer https://github.com/typst-community/typst-install and point to it/export  `export QUARTO_TYPST=/path/to/typst0.11.1`  from their `.zhsrc` or `.bashrc`; this will work for mac/linux, not sure about Windows

**Comment by mvuorre** [comment]
Thanks, really appreciate your feedback around these issues. My view has been that Typst and its Quarto integration are very much WIP and so things will break, but you are right that it could be better indicated in the README etc. I might add something later but would also be very happy if you sent over a PR :)

PS. To me it is a little confusing when this also depends on whether you are rendering from a terminal with the system Quarto/Typst/etc vs. RStudio which has its own. This might suggest requiring an advanced Quarto version instead...
