### ISSUE TITLE
template preprint.docx seems to be empty 

### ISSUE THREAD

**Issue by danieltomasz** [mvuorre/quarto-preprint#21]
Aften  provided docx template in MS Word on MacOS, file seems to be empty.

**Comment by danieltomasz** [comment]
I don't know, I always used the explicit template with styles, but probably your file contain the styles but not the content https://quarto.org/docs/output-formats/ms-word-templates.html

Apa quarto has also almost blank docx in the extension https://github.com/wjschne/apaquarto but they have comment (running title?) and page numbering in this blank template

**Comment by mvuorre** [comment]
Correct. The file contains the required styles and is empty from content. I'm closing this because there's not many reasons to include the content.
