### ISSUE TITLE
Reference section has paragraph breaks

### ISSUE THREAD

**Issue by mvuorre** [mvuorre/quarto-preprint#7]
There should not be additional space between references

<img width="1037" alt="image" src="https://github.com/mvuorre/quarto-preprint/assets/7349270/5a751596-7630-4ef3-99ed-ed23eb7f173d">

**Comment by danieltomasz** [comment]
I fixed this for 0.12 with  `#show bibliography: set par( spacing: 0.65em, leading: 0.65em)`, for `0.11` should be probably something like `#show bibliography: show par: set block( spacing: 0.65em, leading: 0.65em)` but I dont have time for tesing it tonight

**Comment by mvuorre** [comment]
Waiting for Typst 0.12 to be included in Quarto

**Comment by danieltomasz** [comment]
I will check if I can provide solution for 0.11, then update one of my PRs

**Comment by danieltomasz** [comment]
Seems to work both for 0.12 and 0.11
```typst
// block settings in bibliography

#if sys.version >= version(0, 12, 0) {
    show bibliography: set par(spacing: 0.65em, leading: 0.65em)
  } else {
    show bibliography: set block(spacing: 0.65em)
  }
```

**Comment by mvuorre** [comment]
Thanks for looking into this! Fixed now. (It's a judgment call re proper value--my thinking was to make all references appear as lines in the same paragraph.)
